### ISSUE TITLE
Disband AI mercenary_companies aka "prevent vanilla eu4 debt spiral"

### ISSUE THREAD

**Issue by Mxt-dot** [Mxt-dot/BetterAI#12]
Currently the AI is running into debt spirals due to hiring (and not disbanding) mercenary_companies. 

Often they hire 30k troops in early game which leads to a huge deficit of more than 10 ducats per month, while having enough manpower to sustain a regular army. All of this while sitting at 80+% filled troop limit.

Similar solution is needed for ships since the AI likes to suicide ships into superior enemies and after that spend an entire fortune on another range of ships. Does not necessarily cause a debt spiral, but contributes to it.

Are there any commands which allow for deletion of mercenary_units? Any commands for deletion of ships?

Only known is kill_units which is only applicable to inf/cav/art units, so does NOT affect mercenary units.

**Comment by Mxt-dot** [comment]
A fix was put into place which prevents the AI from spiraling into debt hell. 

Though still, this would be a nice addition to the mod if there was a method to manually disband the merc armies

**Comment by stackpoint** [comment]
They actually added "disband_mercenary_company = THIS" that you could use as kill_units.

**Comment by stackpoint** [comment]
This is an example that I found on the forums that should work:  https://forum.paradoxplaza.com/forum/threads/mercs-reason-for-performance-issues-in-1-30.1402395/

**Comment by Mxt-dot** [comment]
Thanks a ton for the recommendation.

I contacted him on steam and he will upload an updated version of this which I'll incorporate into the project

**Comment by AgainstBronchitis** [comment]
So has this now been incorporated? I downloaded the mod and the comment in the event file says it's not working.

**Comment by Mxt-dot** [comment]
Yeah it's not yet included, I paused the development of the mod for a couple weeks, but not long and I'll be back in full swing :) 

One of the first things I'll implement will be this one right here. Until then I can review pull requests and actual contributions from others, that's always welcome.

**Comment by AgainstBronchitis** [comment]
Okay, thanks for the info. So the next version when it's ready will be here on GitHub?

**Comment by Mxt-dot** [comment]
The github project always has the highest priority, all the newest (unofficial) updates are here and the Steam version is a taken from here aswell. Afaik since you commented you'll receive a notification anyway for this issue, so you won't miss it :)

**Comment by AgainstBronchitis** [comment]
Sorry to impose on you more.

How to install it? Just dump it in the EU4/mods folder?

Shouldn't there be a BetterAI.mod file?

Is there a quick way from in game to check if the mod has loaded properly?

**Comment by Mxt-dot** [comment]
Absolutely no problem :) 

So if you want to use it from here, you can go into your mod folder of eu4 and clone the project via git or just dump it in there via download. You're right that you will need to do the BetterAI.mod yourself, but that's due to the uploader in the paradox launcher always creating a new .mod file when I update it on steam, so I got annoyed. Not sure if they fixed it by now.

For the betterAI.mod, you can just copy the descriptor.mod from here, add the line 
path="PATH TO THE BETTERAI FOLDER (including the folder)"
and you should be good to go.

Since I'm always loading it from my local repo I was never in the situation to test it, but that should be basically it :)

> Is there a quick way from in game to check if the mod has loaded properly?

Easiest way is to check the modifier for "Hard" difficulty. If it only grants -1 national unrest, then you're good. Other than that if you're already ingame, check for the forcelimit modifiers for the ages. From age_of_reformation on there should be +% FL modifiers.

Definitely something I should work on, a bit of quality of life improvements, for the quality of life improvements.

Don't hesitate to get back to me, every message is a good message.

**Comment by AgainstBronchitis** [comment]
Thanks!

According to Wiki, the AI unrest modifier in Vanilla on hard is already -1 only?

https://eu4.paradoxwikis.com/Options#Difficulty

**Comment by AgainstBronchitis** [comment]
Thanks, got it.

Not sure if others have the same but in my case, after the installation, the tooltip is offering me to build native buildings as France:

https://imgur.com/a/dDqnCBC

Everything else seems to be fine.

**Comment by Mxt-dot** [comment]
Well that is weird. But you can't actually build the buildings right, it's just the tooltip? If so, does it appear if you deactivate the mod? My assumption is that it's a vanilla tooltip bug.

If you like, you can upload your savefile here in the replies aswell (afaik), because I can't replicate it :/ 

![20200825154436_1](https://user-images.githubusercontent.com/58655660/91182136-1064d200-e6ea-11ea-804c-51f50be1d285.jpg)

**Comment by AgainstBronchitis** [comment]
Yes, it was just the tooltip. I deleted the native buildings file and it's fine now. Your file seems to be a bit different than vanilla which has "trigger" twice each time.

**Comment by Mxt-dot** [comment]
Weird, I'll fix that today :)
This (and other major changes) should be available today/tomorrow on steam.

**Comment by Mxt-dot** [comment]
closing issue since fixed in #24 

AI now disbands mercs :) thanks to Question.

If there's any issues regarding the tooltip still, feel free to open an issue about it (or really, anything). Though I'm fairly confident that everything is alright now.
