### ISSUE TITLE
Fix microfreezes by adding delay to events

### ISSUE THREAD

**Issue by Mxt-dot** [Mxt-dot/BetterAI#16]
The events trigger for too many nations at the same time. Higher meantime_to_happen + lower frequency necessary to prevent microfreezes every ~2weeks, especially for weaker processors.

**Comment by stackpoint** [comment]
Which event is this?

**Comment by Mxt-dot** [comment]
I just received note of stuttering and performance issues. Since there's only events that would make this happen, I assume it's both since the check for forts and mana spending triggers pretty frequently. 

I did some changes already (branches are remote), but I didn't merge yet

**Comment by stackpoint** [comment]
I don't think you need to add any delays to the events. I took a look and it seems like you didn't add a "always = no" to your debtevent outline so it's constantly triggering without actually deleting the units, causing the performance drops.

![image](https://user-images.githubusercontent.com/5704491/87237311-78f12d00-c390-11ea-8735-358179dc9815.png)

**Comment by stackpoint** [comment]
Actually, it seems like manaevent.1 is constantly firing too. Looks like the event is firing too often because it doesn't account for the institution penalty for the mana cap. You may want to use the trigger I made in  https://github.com/Mxt-dot/BetterAI/issues/17

41,503 triggers of manaevent.1 vs 980 triggers in my test mod by 1600

**Comment by Mxt-dot** [comment]
I'll look into #17 and try it out today, though how did you track the amount of calls? (Was it the profiler?)
One of my major gripes was that I didn't know if the event actually triggered for a nation, so I had to look for identifiers ingame.

Also since your solution uses variables and such, how do you actually debug something like this without a proper debugger?

But back to topic: The difference in calls is staggering hah.

**Comment by stackpoint** [comment]
> how did you track the amount of calls?

I added 
```
log = "[This.GetName] eventname.x"
```
 to all your events. It writes the output to the game.log file.

See:
https://eu4.paradoxwikis.com/Commands#Dual_scope 
https://eu4.paradoxwikis.com/Localisation#Variables


> Also since your solution uses variables and such, how do you actually debug something like this without a proper debugger?

Same as above, I output all the major variables using the log command during the debugging phase. Although a minor problem is that log does not work in the trigger scope.


> But back to topic: The difference in calls is staggering hah.

I think the problems start when countries get really behind in tech like the East Asian countries do in the 1550s and the 950 hard limit becomes too low.

**Comment by stackpoint** [comment]
Some discussion regarding fortevent:

- treasury check for buildings are sometimes considered at 1.5x - 2.0x cost so the AI has a buffer in case it needs to spend the money elsewhere
- current_income_balance to check if the ledgers are in the green
- num_of_loans may need to be reduced considering the dire state of AI economy
- is_state_core trigger could limit the scope of fort upgrades to more valuable land
- add_building_construction could be used to add construction time though an instant building would be simpler logistically
- is_at_war check may be needed so fort upgrades don't appear in a duration of a war

**Comment by Mxt-dot** [comment]
Alright, it's been a long time, but I implemented your recommendations and especially your devclicker into [https://github.com/Mxt-dot/BetterAI/tree/12-performanceImprovement](url) and therefore [https://github.com/Mxt-dot/BetterAI/tree/13-disbandMercenaries](url), as well as shifting the fortevents logic into a decision aswell, because it's really elegant.

If you want to try it out, check out [https://github.com/Mxt-dot/BetterAI/pull/24](url)

Everything seems to work as before, just a bit more efficient :) There are other things I would like to add into the fortdecision logic, like strategic placement of forts, but that's out of my scope atm and it's something for another issue.

If you got any further ideas, recommendations or just feedback, I would love to hear it. Otherwise, I'll close the issue tomorrow or so after the merge.

**Comment by Mxt-dot** [comment]
closing, since fixed in #24
