### ISSUE TITLE
Devpushing Feedback

### ISSUE THREAD

**Issue by stackpoint** [Mxt-dot/BetterAI#2]
Had a chance to run a game until 1530 or so.

It definitely looks like the AI is devpushing into institutions. I saw many East Asian and Indian countries pop up with renaissance.

One thing I noticed was that many tribal/native countries were devpushing into feudalism when they could not embrace it without reforming their government first.

It's also interesting to open the ledger and see new world and sub saharan provinces as the highest developed in the world.

**Comment by Mxt-dot** [comment]
Yeah the AI ignores the terrain and devpushes for the same cost no matter the terrain. Otherwise it becomes a mess logically. 

The thing about institutions not being unlocked is something I didn't consider and that exact issue happened at our casual MP session today. Definitely gotta do something about this. Though I think only american natives have a locked "institution" right? Anyway, we also had some nations being able to catch up in tech so they become monsters. Talking about 1k dev year 1600 natives with newest tech...

I think I also saw Sweden devpushing it in our MP, though I actually excluded europe from doing this. Will have to do some testing to figure out if that condition is somehow broken. Thanks for the continuous feedback :)

**Comment by stackpoint** [comment]
> Yeah the AI ignores the terrain and devpushes for the same cost no matter the terrain. Otherwise it becomes a mess logically.

Yeah, I think there is a way to get a cost working using variables but this isn't bad at all. Especially when they weren't doing anything to begin with and it's just quibbling over 200-400 monarch points.

> The thing about institutions not being unlocked is something I didn't consider and that exact issue happened at our casual MP session today. Definitely gotta do something about this. Though I think only american natives have a locked "institution" right? Anyway, we also had some nations being able to catch up in tech so they become monsters. Talking about 1k dev year 1600 natives with newest tech...

Letting the new world countries devpush does make some pretty crazy games. It also makes for some very unpleasant surprises for the colonizers.

I believe "primitives = yes" would cover the new world without affecting colonial nations. According to the [wiki](https://eu4.paradoxwikis.com/Technology#Primitive) "primitives" refers to nations in the following technology groups: 
- North American
- Mesoamerican
- Andean
- South American

> I think I also saw Sweden devpushing it in our MP, though I actually excluded europe from doing this. Will have to do some testing to figure out if that condition is somehow broken. Thanks for the continuous feedback :)

Looks like "continent = europe" requires a province scope rather than a country scope.

**Comment by Mxt-dot** [comment]
Alright, thanks for the "primitives" recommendation, that seems to have fixed it! I had to split the conditions on devpushing into primitives and everything else, as primitives would stop teching up to develop provinces instead. 

Now everything about mana-dev is fixed hopefully, currently running through an observer game to check :) 
The current version is already online

**Comment by stackpoint** [comment]
Looks good. I've noticed you removed the European restriction and extended the timeline by five years, which makes sense because theoretically colonialism can spawn outside of Europe.

I also noticed in an observer game that an AI devpushed a province to spawn feudalism while it was occupied and immediately lost it (and the 20 extra dev) in the peace deal. You may want to restrict the big devpush institution spawn until "is_at_war = no".

**Comment by Mxt-dot** [comment]
Oh, good point... Must have been a pleasant surprise for the winning AI.

Will change it :)

**Comment by Mxt-dot** [comment]
At last it was fixed, so I'll close this issue :) if there are any issues related to this I'll open it up again (or create a new issue)
