### ISSUE TITLE
add toggle to all decisions / make AI only

### ISSUE THREAD

**Issue by Mxt-dot** [Mxt-dot/BetterAI#28]
The decisions don't have a title, description and bother the people with reminders. Make it more userfriendly

**Comment by stackpoint** [comment]
Just a simple ai check should work since they should be all for ai

```
ai = yes
```

**Comment by Mxt-dot** [comment]
hmm yeah I could do that, though perhaps there's also a benefit to it if some of the things are available to the player aswell, like a reminder to upgrade forts.
