### ISSUE TITLE
Change ideas priority ranking

### ISSUE THREAD

**Issue by Mxt-dot** [Mxt-dot/BetterAI#30]
Sometimes, the AI has plenty of quantity and no quality, but decides to pick quantity nontheless. 

I'm thinking of 1,4m+ ottomans picking quantity on top (instead of quality).

**Comment by Unoffe** [comment]
Picking quantity instead of any other idea group is current meta. Quantity -> innovative -> quality - most useful group of groups so it's better to leave it.

**Comment by Mxt-dot** [comment]
hmm I don't think this is applicable to every situation though. If you have 1m troops then you don't need more of them, especially considering that the AI is really bad at handling individual stacks :D 

The AI is better off having 800k with high quality instead of 1,1m imo.
